export { default as AppComponent } from './app/app.component';
export { default as StartScreenComponent } from './start-screen/start-screen.component';
export { default as GameBoardComponent } from './game-board/game-board.component';
export { default as BoardComponent } from './game-board/board/board.component';
export { default as BoardRowComponent } from './game-board/board/board-row.component';
export { default as CardComponent } from './game-board/card/card.component';
export { default as DeckComponent } from './game-board/deck/deck.component';
export { default as SuitsComponent } from './game-board/suits/suits.component';
export { default as SuitComponent } from './game-board/suits/suit.component';
